version: "2"
services:
  ossimport2:
    restart: unless-stopped
    image: kdaye/ossimport2
    container_name: oss
    volumes:
      - ./conf/local_job.cfg:/root/ms/conf/local_job.cfg
      - /data:/data
    network_mode: bridge
